export const types = {
  SET_SEARCH: 'ui/SET_SEARCH',
  OPEN_EDITOR: 'ui/OPEN_EDITOR',
  CLOSE_EDITOR: 'ui/CLOSE_EDITOR',
  REQUEST_CONFIRM_DELETE: 'ui/REQUEST_CONFIRM_DELETE',
  CANCEL_CONFIRM_DELETE: 'ui/CANCEL_CONFIRM_DELETE',
  SHOW_TOAST: 'ui/SHOW_TOAST',
  DISMISS_TOAST: 'ui/DISMISS_TOAST',
} as const;
