const MODULE = 'USER_MODULE/';

export default {
  SET_FIRSTNAME: `${MODULE}/SET_FIRSTNAME`,
  SET_LASTNAME: `${MODULE}/SET_LASTNAME`,
  SET_ADDRESS: `${MODULE}/SET_ADDRESS`,
  FETCH_PROFILE: `${MODULE}/FETCH_PROFILE`,
};
